version: "3"

services:
  # OpenVPN Community Edition container
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped

  # PostgreSQL 17 container
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vpnadmin
      - POSTGRES_PASSWORD=vpnsecurepass
      - POSTGRES_DB=vpn_dashboard
    restart: unless-stopped

  # Dashboard server (our application)
  dashboard:
    build: .
    container_name: vpn-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - openvpn
    environment:
      - DATABASE_URL=postgres://vpnadmin:vpnsecurepass@postgres:5432/vpn_dashboard
      - OPENVPN_CONFIG_DIR=/etc/openvpn
    volumes:
      - ./data/openvpn:/etc/openvpn
    restart: unless-stopped
