services:
  # OpenVPN Community Edition container
  openvpn:
    build:
      context: ./openvpn
      dockerfile: Dockerfile.openvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - openvpn-data:/etc/openvpn
    ports:
      - "1194:1194/udp"
      - "7505:7505/tcp"  # Management interface
    environment:
      - DEBUG=1
      - OVPN_SERVER_URL=udp://localhost  # Change to your server's public IP/domain
      - OVPN_NETWORK=192.168.255.0/24
      - OVPN_DNS=8.8.8.8
      - OVPN_CIPHER=AES-256-GCM
      - OVPN_AUTH=SHA256
    restart: unless-stopped
    networks:
      - vpn-network

  # PostgreSQL 17 container
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vpnadmin
      - POSTGRES_PASSWORD=vpnsecurepass
      - POSTGRES_DB=vpn_dashboard
    restart: unless-stopped
    networks:
      - vpn-network

  # Dashboard server (our application)
  dashboard:
    build: .
    container_name: vpn-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - openvpn
    environment:
      - DATABASE_URL=postgres://vpnadmin:vpnsecurepass@postgres:5432/vpn_dashboard
      - OPENVPN_CONFIG_DIR=/etc/openvpn
      - OPENVPN_STATUS_LOG=/etc/openvpn/openvpn-status.log
      - OPENVPN_MANAGEMENT_HOST=openvpn
      - OPENVPN_MANAGEMENT_PORT=7505
      - EASYRSA_PATH=/usr/share/easy-rsa
    volumes:
      - openvpn-data:/etc/openvpn
    restart: unless-stopped
    networks:
      - vpn-network

volumes:
  openvpn-data:

networks:
  vpn-network:
    driver: bridge
